INFO-2023-12-15 00:40:40,187 - xhome.py[line:87]:配置文件读取成功,端口:80,协议:HTTP/1.1,IP:127.0.0.1

DEBUG-2023-12-15 00:40:41,088 - __init__.py[line:320]:matplotlib data path: C:\Users\xjh\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\mpl-data

DEBUG-2023-12-15 00:40:41,092 - __init__.py[line:320]:CONFIGDIR=C:\Users\xjh\.matplotlib

DEBUG-2023-12-15 00:40:41,093 - __init__.py[line:1494]:interactive is False

DEBUG-2023-12-15 00:40:41,093 - __init__.py[line:1495]:platform is win32

DEBUG-2023-12-15 00:40:41,132 - __init__.py[line:320]:CACHEDIR=C:\Users\xjh\.matplotlib

DEBUG-2023-12-15 00:40:41,133 - font_manager.py[line:1543]:Using fontManager instance from C:\Users\xjh\.matplotlib\fontlist-v330.json

DEBUG-2023-12-15 00:40:42,394 - tpu_cluster_resolver.py[line:34]:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.

DEBUG-2023-12-15 00:40:42,564 - __init__.py[line:47]:Creating converter from 7 to 5

DEBUG-2023-12-15 00:40:42,564 - __init__.py[line:47]:Creating converter from 5 to 7

DEBUG-2023-12-15 00:40:42,564 - __init__.py[line:47]:Creating converter from 7 to 5

DEBUG-2023-12-15 00:40:42,564 - __init__.py[line:47]:Creating converter from 5 to 7

WARNING-2023-12-15 00:40:44,055 - module_wrapper.py[line:149]:From C:\Users\xjh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.


DEBUG-2023-12-15 00:40:44,380 - xhome.py[line:91]:#初始化服务器......#

INFO-2023-12-15 00:40:44,380 - xhome.py[line:115]:服务器初始化成功,端口:80,协议:HTTP/1.1,IP:127.0.0.1

INFO-2023-12-15 00:40:44,380 - xhome.py[line:215]:等待事件发生...

DEBUG-2023-12-15 00:40:44,575 - xhome.py[line:120]:服务器接收到新连接,IP:('127.0.0.1', 65253)

INFO-2023-12-15 00:40:44,575 - xhome.py[line:215]:等待事件发生...

DEBUG-2023-12-15 00:40:49,497 - xhome.py[line:120]:服务器接收到新连接,IP:('127.0.0.1', 65258)

INFO-2023-12-15 00:40:49,498 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:40:49,501 - xhome.py[line:222]:套接字响应('127.0.0.1', 65253)

INFO-2023-12-15 00:40:49,501 - xhome.py[line:166]:接收数据中...

INFO-2023-12-15 00:40:49,501 - xhome.py[line:179]:数据接收中断 IP:('127.0.0.1', 65253)

DEBUG-2023-12-15 00:40:49,501 - xhome.py[line:208]:请求头解析成功

INFO-2023-12-15 00:40:49,501 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:40:49,663 - xhome.py[line:222]:套接字响应('127.0.0.1', 65258)

INFO-2023-12-15 00:40:49,663 - xhome.py[line:166]:接收数据中...

INFO-2023-12-15 00:40:49,664 - xhome.py[line:179]:数据接收中断 IP:('127.0.0.1', 65258)

DEBUG-2023-12-15 00:40:49,664 - xhome.py[line:208]:请求头解析成功

INFO-2023-12-15 00:40:49,664 - xhome.py[line:215]:等待事件发生...

DEBUG-2023-12-15 00:40:56,208 - xhome.py[line:120]:服务器接收到新连接,IP:('127.0.0.1', 65259)

INFO-2023-12-15 00:40:56,208 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:40:56,208 - xhome.py[line:222]:套接字响应('127.0.0.1', 65259)

INFO-2023-12-15 00:40:56,208 - xhome.py[line:166]:接收数据中...

INFO-2023-12-15 00:40:56,208 - xhome.py[line:179]:数据接收中断 IP:('127.0.0.1', 65259)

DEBUG-2023-12-15 00:40:56,208 - xhome.py[line:208]:请求头解析成功

DEBUG-2023-12-15 00:40:56,210 - connectionpool.py[line:244]:Starting new HTTP connection (1): api.tushare.pro:80

DEBUG-2023-12-15 00:40:57,045 - connectionpool.py[line:546]:http://api.tushare.pro:80 "POST / HTTP/1.1" 200 None

WARNING-2023-12-15 00:41:01,444 - module_wrapper.py[line:149]:From C:\Users\xjh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.


WARNING-2023-12-15 00:41:01,843 - module_wrapper.py[line:149]:From C:\Users\xjh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.


WARNING-2023-12-15 00:41:02,398 - module_wrapper.py[line:149]:From C:\Users\xjh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.


DEBUG-2023-12-15 00:41:06,325 - attrs.py[line:205]:Creating converter from 5 to 3

INFO-2023-12-15 00:41:10,619 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:41:30,620 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:41:50,625 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:42:10,633 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:42:30,642 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:42:50,654 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:43:10,656 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:43:30,669 - xhome.py[line:215]:等待事件发生...

INFO-2023-12-15 00:43:50,681 - xhome.py[line:215]:等待事件发生...

